config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'users#index'
  get 'api/users', to: 'users#index', defaults: { format: 'json' }
  post 'users/import' => 'users#import'
  post 'tracks/import' => 'tracks#import'
  post 'playlists/import' => 'playlists#import'
  get 'users/:id/playlists' => 'users#playlists', as: :user_playlists

  root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tracks
end

app/models/track.rb
class Track < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def import
    if params[:file]
      import_playlists_service.run(params[:file].tempfile)
      flash[:notice] = 'File imported successfully'
    else
      flash[:error] = 'File is required'
    end
    redirect_to users_path
  end

  def user_repository
    @user_repository ||= ActiveRecordUserRepository.new
  end

  def track_repository
    @track_repository ||= ActiveRecordTrackRepository.new
  end

  def playlist_repository
    @playlist_repository ||= ActiveRecordPlaylistRepository.new
  end

  private

  def import_playlists_service
    @import_playlists_service ||= Playlists::Services::ImportPlaylistsService.new(
      user_repository, track_repository, playlist_repository
    )
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def import
    if params[:file]
      import_tracks_service.run(params[:file].tempfile)
      flash[:notice] = 'File imported successfully'
    else
      flash[:error] = 'File is required'
    end
    redirect_to users_path
  end

  def track_repository
    @track_repository ||= ActiveRecordTrackRepository.new
  end

  private

  def import_tracks_service
    @import_tracks_service ||= Playlists::Services::ImportTracksService.new(track_repository)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = list_user_service.run
  end

  def import
    if params[:file]
      import_users_service.run(params[:file].tempfile)
      flash[:notice] = 'File imported successfully'
    else
      flash[:error] = 'File is required'
    end
    redirect_to users_path
  end

  def playlists
    @playlists = list_playlists_from_user_service.run(params[:id])
  end

  def user_repository
    @user_repository ||= ActiveRecordUserRepository.new
  end

  def playlist_repository
    @playlist_repository ||= ActiveRecordPlaylistRepository.new
  end

  private

  def import_users_service
    @import_users_service ||= Playlists::Services::ImportUsersService.new(user_repository)
  end

  def list_user_service
    @user_service ||= Playlists::Services::ListUsersService.new(user_repository)
  end

  def list_playlists_from_user_service
    @list_playlists_from_user_service = Playlists::Services::ListPlaylistsFromUserService.new(playlist_repository)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playlists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= form_tag users_import_path, method: :post, multipart: true, class: 'form-inline' do %>
  <%= label_tag 'file', 'Import Users CSV File', class: 'font-weight-bold my-1 mr-2' %>
  <%= file_field_tag 'file', class: 'my-1 mr-sm-2', required: true %>
  <%= submit_tag 'Send', class: 'btn btn-primary my-1 mr-sm-2' %>
<% end %>

<%= form_tag tracks_import_path, method: :post, multipart: true, class: 'form-inline' do %>
  <%= label_tag 'file', 'Import Tracks CSV File', class: 'font-weight-bold my-1 mr-2' %>
  <%= file_field_tag 'file', class: 'my-1 mr-sm-2', required: true %>
  <%= submit_tag 'Send', class: 'btn btn-primary my-1 mr-sm-2' %>
<% end %>

<%= form_tag playlists_import_path, method: :post, multipart: true, class: 'form-inline' do %>
  <%= label_tag 'file', 'Import Paylists CSV File', class: 'font-weight-bold my-1 mr-2' %>
  <%= file_field_tag 'file', class: 'my-1 mr-sm-2', required: true %>
  <%= submit_tag 'Send', class: 'btn btn-primary my-1 mr-sm-2' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Username</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Playlists', user_playlists_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/playlists.html.erb
<% @playlists.each do |playlist| %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Playlist:</th>
        <th scope="col" colspan="6"><%= playlist.name %></th>
      </tr>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Interpret</th>
        <th scope="col">Album</th>
        <th scope="col">Track</th>
        <th scope="col">Year</th>
        <th scope="col">Genre</th>
      </tr>
    </thead>
    <tbody>
      <% playlist.tracks.each do |track| %>
        <tr>
          <td><%= track.id %></td>
          <td><%= track.title %></td>
          <td><%= track.interpret %></td>
          <td><%= track.album %></td>
          <td><%= track.track %></td>
          <td><%= track.year %></td>
          <td><%= track.genre %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>